---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=django-imager.conf dest=/etc/init/django-imager.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=django-imager state=restarted
